log_file="server.log"
log_level="DEBUG"

[server.dialin]
enabled=true
module="dialin:DialInServer"
port=3333
host="127.0.0.1"
max_connection=16
login_retry=3
login_timeout=120

[server.dialin.conn.alpine]
host="127.0.0.1"
port=8122
username="frank"
term="ansi"

[server.dialin.conn.termux]
host="127.0.0.1"
port=8022
term="ansi"

