log_file="server.log"
log_level="DEBUG"
pid_file="/data/data/com.termux/files/usr/tmp/server.pid"
daemonize=true

[server.dialin]
enabled=true
module="dialin:DialInServer"
port=3333
host="127.0.0.1"
max_connection=16
login_retry=3
login_timeout=120

[server.dialin.conn.frank]
host="127.0.0.1"
port=8122
term="ansi"

[server.dialin.conn.termux]
host="127.0.0.1"
port=8022
term="ansi"

