#!/usr/bin/env python3
#encoding=UTF-8

from sysinfo import SysInfo;

if __name__ == '__main__':
    sysinfo = SysInfo();
    result = sysinfo.fetch();
    if 'cpu_temp' in result:
        print('CPU Temperature: %d C' % result['cpu_temp']);
    if 'gpu_temp' in result:
        print('GPU Temperature: %d C' % result['gpu_temp']);
    if 'cpu_usage' in result:
        print('CPU Usage: %.1f%%'  % (result['cpu_usage']['overall'] * 100));
    if 'mem_usage' in result:
        print('Memory Usage: %.1f%%' % (result['mem_usage'] * 100));
    if 'boot_time' in result:
        print('Boot Time: %s' % result['boot_time'].strftime('%Y-%m-%dT%H:%M:%S'));
    if ('battery_level' in result) and (None != result['battery_level']):
        print('Battery Level: %d%%' % result['battery_level']);
    exit(0);

